[[navbar]]
    identifier = "documentation"
    weight = 1
    name = "文档"
    url = "documentation/"
    pre = "<span class=\"icon\"><i class=\"fas fa-book\"></i></span>"


[[navbar]]
    identifier = "github"
    weight = 99
    name = "GitHub"
    url = "https://github.com/wayn3h0/hugo-bulma"
    pre = "<span class=\"icon\"><i class=\"fab fa-github\"></i></span>"

[[quicklinks]]
    identifier = "documentation"
    weight = 1
    name = "文档"

[[quicklinks]]
    identifier = "follow"
    weight = 99
    name = "关注"

[[quicklinks]]
    identifier = "twitter"
    parent = "follow"
    weight = 1
    name = "Twitter"
    url = "#"
    pre = "<span class=\"icon\"><i class=\"fab fa-twitter\"></i></span>"

[[quicklinks]]
    identifier = "facebook"
    parent = "follow"
    weight = 2
    name = "Facebook"
    url = "#"
    pre = "<span class=\"icon\"><i class=\"fab fa-facebook\"></i></span>"


